In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
a1 = np.array([3.14,2,3,11])
a1

array([ 3.14,  2.  ,  3.  , 11.  ])

In [6]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

shape: dòng, cột

In [7]:
a2.shape

(2, 3)

In [8]:
a2.dtype 

dtype('int64')

In [9]:
a2.size

6

In [103]:
#Dao chieu
x2=np.random.randint(0,10,(3,4))


In [104]:
x2.T

array([[9, 3, 0],
       [0, 2, 0],
       [4, 7, 4],
       [7, 2, 5]])

CREATE NUMPY ARRAY FROM SCRATCH

zeros, ones,full , arange, linspace

In [10]:
np.zeros([2,4], dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [13]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [14]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

random

In [15]:
#seed for reproducibility
np.random.seed(0)

np.random.random((4,4))



array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [16]:
#normal (min, do lech, size)

np.random.normal(0,1,(3,3))


array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [17]:
np.random.randint(0,20,(4,5))

array([[ 2,  0,  0,  4,  5],
       [ 6,  8, 17, 15,  4],
       [ 9, 10,  1,  1,  7],
       [ 9,  3,  6, 11, 14]])

ARRAY INDEXING AND SLICING

One-dimensional subarray

In [18]:
x1= np.random.randint(1,20,size = 7)
x1

array([19,  1, 15,  4, 13, 11, 12])

In [19]:
x1[4]    , x1[-1]

(13, 12)

Multi-dimenson array

In [20]:
x2=np.random.randint(0,10,(3,4))
x2

array([[4, 6, 4, 4],
       [3, 4, 4, 8],
       [4, 3, 7, 5]])

In [21]:
x2[2,3]

5

In [22]:
x2[2,3]=6
x2

array([[4, 6, 4, 4],
       [3, 4, 4, 8],
       [4, 3, 7, 6]])

Slicing

In [23]:
x1

array([19,  1, 15,  4, 13, 11, 12])

In [24]:
x1[0:3]

array([19,  1, 15])

In [25]:
x2[:2,:3]

array([[4, 6, 4],
       [3, 4, 4]])

RESHAPING OF ARRAYS AND TRANSPOSE

In [52]:
grid = np.arange(1,17)
grid.shape

(16,)

In [53]:
grid

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [27]:
grid.reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

ARRAY CONCATENATION AND SPLIITING

concatenation

In [28]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
np.concatenate((x,y)) #axis = 0 by DEFAULT ( noi theo chieu ngang)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
grid = np.array([[1,2,3,4], 
                [5,6,7,8]])
np.concatenate((grid,grid), axis = 1) #axis = 1 (noi theo chieu doc)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

In [30]:
#vstack
x= np.array([1,2,3,4])
grid = np.array([[3,4,1,2], 
                [8,5,7,9]])
np.vstack((x,grid))

array([[1, 2, 3, 4],
       [3, 4, 1, 2],
       [8, 5, 7, 9]])

In [33]:
#hstack
y = np.array([[10],
              [12]])
grid = np.array([[3,4,1,2], 
                [8,5,7,9]])
np.hstack((y,grid))

array([[10,  3,  4,  1,  2],
       [12,  8,  5,  7,  9]])

splitting

In [35]:
x= np.array([1,2,3,4,5,6,7,8])
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6, 7, 8])]

In [42]:
x= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
x1,x2,x3,x4 = np.split(x,[4,6,11])
x1,x2,x3,x4


(array([1, 2, 3, 4]),
 array([5, 6]),
 array([ 7,  8,  9, 10, 11]),
 array([12, 13, 14]))

(array([1, 2, 3]), array([4, 5, 6]), array([ 7,  8,  9, 10, 11]))

BROADCASTING AND VECTORIZED OPERATIONS

In [43]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [44]:
a+3 #broadcasting

array([3, 4, 5, 6])

In [48]:
b = np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
b + 2


array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [50]:
a+b

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [57]:
c = np.arange(4).reshape(4,1)
c

array([[0],
       [1],
       [2],
       [3]])

In [58]:
a + c

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

MANIPULATING AND COMPARING ARRAYS

In [59]:
list_number = [1,2,3]
ll = np.array(list_number)
ll

array([1, 2, 3])

In [60]:
sum(ll) #Python sum()

6

In [61]:
np.sum(ll) #Numpy sum()

6

In [69]:
#Create a massive Numpy array 
massive_array = np.random.random(1000)
massive_array[:10]

array([0.62206135, 0.98098753, 0.60698098, 0.22526563, 0.26540702,
       0.19743279, 0.77683124, 0.49679979, 0.11359702, 0.87371754])

In [71]:
%timeit sum(massive_array) #Python build-in function sum()
%timeit np.sum(massive_array) #Numpy build-in function sum()

88.2 µs ± 5.85 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
4.44 µs ± 179 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [72]:
np.mean(massive_array) #gia tri trung binh

0.503751961626802

In [73]:
np.min(massive_array)

0.0028745122595924544

In [75]:
np.max(massive_array)

0.9991426727880106

In [76]:
dog_height = [600,400,300,150,550]
dog_height = np.array(dog_height)
#phuong sai
np.std(dog_height)
#do lech chuan
np.var(dog_height)

27000.0

SORTING ARRAYS

In [77]:
#np.sort use quicksort algorithm
x = np.array([5,7,2,3,1,8,4])
np.sort(x)

array([1, 2, 3, 4, 5, 7, 8])

In [78]:
#sort va hien thi vi tri cua phan tu
np.argsort(x)

array([4, 2, 3, 6, 0, 1, 5])

Sorting along rows or columns

In [79]:
np.random.seed(0)
MatA = np.random.randint(0,10,(4,6))
MatA

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9]])

In [81]:
#Sort theo column
np.sort(MatA, axis=0) 

array([[3, 0, 1, 3, 7, 6],
       [5, 1, 2, 4, 7, 7],
       [8, 5, 3, 6, 7, 9],
       [8, 8, 5, 9, 8, 9]])

In [ ]:
#Sort theo row
np.sort(MatA, axis = 1)

EXAMPLE

In [82]:
#Number of jars sold
np.random.seed(0)
sales_amounts = np.random.randint(0,20,(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [84]:
#Create weekly sales DataFrames
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts,index = ['Mon','Tue','Wed','Thu','Fri'], 
                            columns = ['Amond Butter','Peanut Butter','Cashew Butter'])
weekly_sales

Amond Butter  Peanut Butter  Cashew Butter
Mon            12             15              0
Tue             3              3              7
Wed             9             19             18
Thu             4              6             12
Fri             1              6              7

In [92]:
#create a price array 
prices = np.array([10,8,12])
butter_price =  pd.DataFrame(prices.reshape(1,3), index =['Price'], columns = ['Amond Butter','Peanut Butter','Cashew Butter'])
butter_price

Amond Butter  Peanut Butter  Cashew Butter
Price            10              8             12

In [106]:
#dot : tich vo huong
total_price = weekly_sales.dot(butter_price.T)
total_price

Price
Mon    240
Tue    138
Wed    458
Thu    232
Fri    142

In [107]:
weekly_sales['Total Price'] = total_price
weekly_sales

Amond Butter  Peanut Butter  Cashew Butter  Total Price
Mon            12             15              0          240
Tue             3              3              7          138
Wed             9             19             18          458
Thu             4              6             12          232
Fri             1              6              7          142